_import: configs/base/train_base.yaml

boat:
  _target_: 'rhino.boats.vector_quantization.base_vector_quantization_boat.BaseVectorQuantizationBoat'

  models:
    latent_encoder:
      path: 'rhino.nn.wrappers.autoencoder_kl_wrapper'   # Path to import the model class
      name: 'AutoencoderKLWrapper'              # Name of the model class to use
      pretrained: 'stabilityai/sd-vae-ft-mse'  # Example: A common pretrained VAE from Stable Diffusion
    
    vector_quantizer:
      path: 'rhino.nn.vector_quantization.pixel_vector_quantizer'
      name: 'PixelVectorQuantizer'
      params:
        num_codes: 4096
        dim: 4
        eps: 1e-5
  
  losses: {}

optimization: 
    
  use_ema:
    ema_decay: 0.9995
    ema_start: $ema_start

logging:
  root_dir: 'work_dirs'
  name: $experiment_name
  loggers:
    tensorboard:
      path: 'trainer.loggers.tensorboard'
      name: 'TensorBoardLogger'
      params:
        log_dir: 'work_dirs'
        name: $experiment_name

trainer: 
  devices: $devices
  max_epochs: 200
  val_check_epochs: 1
  state_save_epochs: 1
  visualization:
    save_images: true
    wnb: [0.5, 0.5]  # for visualization

validation: 
  save_images: true
  num_vis_samples: 4
  use_reference: true
  target_metric_name: psnr
  metrics:
    psnr:
      path: 'torchmetrics.image'
      name: 'PeakSignalNoiseRatio'
      params:
        data_range: 2.0
    ssim:
      path: 'torchmetrics.image'
      name: 'StructuralSimilarityIndexMeasure'
      params: {}

# Data configuration
data:
  path: trainer.data_modules.image_data_module
  name: DistTrainDistValidDataModule
  config: 
    train_dataloader:
      dataset:
        path: 'trainer.torch_datasets.basic_image_dataset'
        name: 'BasicImageDataset'         # Name of the model class to use
        params:
          # max_dataset_size: 256
          folder_paths: $train_folder_paths
          data_prefix:
            gt: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt]
            - type: Normalize
              keys: [gt]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: $train_batch_size
      num_workers: $num_workers
      pin_memory: false
      persistent_workers: true
      sampler:
        type: DefaultSampler
        shuffle: true

    # Validation dataloader configuration
    valid_dataloader:
      dataset:
        path: 'trainer.torch_datasets.basic_image_dataset'           # Path to import the model class
        name: 'BasicImageDataset'         # Name of the model class to use
        params:
          max_dataset_size: 32
          folder_paths: $valid_folder_paths
          data_prefix:
            gt: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt]
            - type: Normalize
              keys: [gt]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: $valid_batch_size
      num_workers: $num_workers
      pin_memory: false
      persistent_workers: true
      sampler:
        type: DefaultSampler
        shuffle: true


callbacks: 
  - path: trainer.callbacks.state_cleaner
    name: KeepTopKStateCallback
    params:
      top_k: 5

_vars:

  devices: [0, 1, 2, 3]

  train_batch_size: 128
  valid_batch_size: 8
  num_workers: 16

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256

  experiment_name: vq_ffhq_256

  ema_start: 0