_import: configs/base/train_base_sr3.yaml

boat:
  path: 'rhino.diffusers.boats.conditioned.pixel_diffusing'
  name: 'ConditionedPixelDiffusionBoat'
  
  context_encoder:
    path: torch.nn
    name: Upsample
    params:
      size: $sample_size

_vars:

  device: 'cuda:3'

  sample_channels: 3
  condition_channels: 3
  out_channels: 3
  sample_size: [256, 256]

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    ctx: data/ffhq/ffhq_imgs/ffhq_32
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256
    ctx: data/celeba/subsets/celeba_32

  experiment_name: sr3_unet_ddim_ffhq_32_256

  ema_start: 0