_import: configs/base/train_base_sr3.yaml

boat:
  path: 'rhino.boats.diffusions.base_diffusion_boat'
  name: 'BaseDiffusionBoat'            

  latent_encoder:
    path: 'rhino.nn_wrappers.autoencoder_kl_wrapper' 
    name: 'AutoencoderKLWrapper'
    pretrained: 'stabilityai/sd-vae-ft-mse'

  context_encoder:
    path: torch.nn
    name: Identity
    params: {}

_vars:

  device: 'cuda:2'

  sample_channels: 4
  sample_size: 32
  condition_channels: 3
  out_channels: 4
  train_batch_size: 96
  valid_batch_size: 32

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    cond: data/ffhq/ffhq_imgs/ffhq_32
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256
    cond: data/celeba/subsets/celeba_32

  experiment_name: sr3_unet_ldm_ffhq_32_256

  ema_start: 0