_import: configs/base/train_base_sr3.yaml

boat:
  path: 'rhino.boats.diffusions.base_diffusion_boat'
  name: 'BaseDiffusionBoat'

  hooks:
    type: 'rhino.helpers.hooks.basic_hooks.named_forward_hook'
    model_layer_names: 
      'net': ['transformer_blocks.3.ff.net.2']

  net:
    path: 'rhino.nn.wrappers.dit_2d_flexible_wrapper'
    name: 'DiT2DFlexibleWrapper'
    config:
      mode: 'concat'
      sample_size: 4
      sample_channels: 4
      patch_size: 1
      num_layers: 8
      condition_channels: 3
      out_channels: 4
      num_embeds_ada_norm: 1
      attention_head_dim: 64
      num_attention_heads: 8
      norm_num_groups: 32
      norm_eps: 0.00001

  latent_encoder:
    path: 'rhino.nn.wrappers.autoencoder_kl_wrapper' 
    name: 'AutoencoderKLWrapper'
    pretrained: 'stabilityai/sd-vae-ft-mse'

  context_encoder:
    path: torch.nn
    name: Identity
    params: {}

  loss:
    net:
      path: 'rhino.losses.wrappers.repa_loss'
      name: 'REPALoss'
      params: 
        feature_dim: 512
        target_dim: 768
data: 
  path: trainer.data_modules.image_data_module
  name: SimpleTrainValidDataModule
  config: 
    train_dataloader: 
      dataset:
        path: 'trainer.torch_datasets.basic_image_dataset'
        name: 'BasicImageDataset'
        params: 
          folder_paths:
            gt: data/ffhq/ffhq_imgs/ffhq_256
            cond: data/ffhq/ffhq_imgs/ffhq_32
            fx: data/ffhq/ffhq_dinov2_base_npz/ffhq_256
          extensions:
            gt: [png, jpg]
            cond: [png, jpg]
            fx: [npz]
          data_prefix:
            gt: ''
            cond: ''
            fx: ''
          pipeline:
            - type: LoadImageFromFile
              keys: [gt, cond]
            - type: LoadArrayFromNpz
              keys: [fx]
            - type: Normalize
              keys: [gt, cond]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: 16
      num_workers: 16
      pin_memory: false
      persistent_workers: false
      sampler:
        type: DefaultSampler
        shuffle: true
    
    valid_dataloader: 
      dataset: 
        path: 'trainer.torch_datasets.basic_image_dataset'
        name: 'BasicImageDataset'
        params: 
          folder_paths: 
            gt: data/celeba/subsets/celeba_256
            cond: data/celeba/subsets/celeba_32
          data_prefix:
            gt: ''
            cond: ''
          extensions:
            gt: [png, jpg]
            cond: [png, jpg]
          pipeline:
            - type: LoadImageFromFile
              keys: [gt, cond]
            - type: Normalize
              keys: [gt, cond]
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]
      batch_size: 32
      num_workers: 32
      persistent_workers: true
      sampler:
        type: DefaultSampler
        shuffle: true

_vars:

  device: 'cuda:2'
  experiment_name: sr3_dit_dinov2_base_ffhq_32_256
  ema_start: 0