# sr3_ddim_implementation.yaml
# Implementation configuration for SR3 DDIM model, inheriting from base configuration

# Importing the base configuration
_import: configs/base/train_base_sr3.yaml

boat:

  context_encoder:
    path: torch.nn
    name: Upsample
    params:
      size: $sample_size

_vars:

  device: 'cuda:3'

  sample_channels: 3
  condition_channels: 3
  out_channels: 3
  sample_size: [128, 128]
  batch_size: 32

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_128
    ctx: data/ffhq/ffhq_imgs/ffhq_16
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_128
    ctx: data/celeba/subsets/celeba_16

  experiment_name: sr3_unet_ddim_ffhq_16_128

  ema_start: 0