_import: configs/base/train_base_ddim.yaml

boat:
  path: 'rhino.boats.diffusion.base_diffusion_boat'
  name: 'BaseDiffusionBoat'
  
  encoder:
    path: 'rhino.autoencoders.networks.autoencoder_wrappers'   # Path to import the model class
    name: 'AutoencoderKLWrapper'              # Name of the model class to use
    pretrained: 'stabilityai/sd-vae-ft-mse'  # Example: A common pretrained VAE from Stable Diffusion

_vars:

  devices: [0, 1]

  batch_size: 16

  in_channels: 4
  out_channels: 4
  sample_size: [256, 256]

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256

  experiment_name: unet_ldm_ffhq_256

  ema_start: 0