_import: configs/base/train_base_ddim.yaml

_vars:

  device: 'cuda:3'

  in_channels: 3
  out_channels: 3
  sample_size: [256, 256]

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256

  experiment_name: unet_ddim_ffhq_256

  ema_start: 0