_import: configs/base/train_base_disc.yaml

_vars:

  net:
      path: 'rhino.baked_nn.sisr.hat.hat'
      name: 'HAT'
      params: 
        upscale: 8
        img_size: 64
        embed_dim: 96
        depths: [4, 4, 4, 4]
        num_heads: [6, 6, 6, 6]
        window_size: 16
        upsampler: 'pixelshuffle'

  losses: 
      net:
      path: 'rhino.nn.losses.wrappers.pixel_loss'
      name: 'PixelLoss'
      params: {}

  max_epochs: 150

  devices: [3]

  train_batch_size: 512
  valid_batch_size: 32

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    lq: data/ffhq/ffhq_imgs/ffhq_32
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256
    lq: data/celeba/subsets/celeba_32

  experiment_name: hat_ffhq_32_256

  ema_start: 0