_import: configs/base/train_base_gan.yaml

boat:
  path: 'rhino.boats.gan.regularized_gan_boat'
  name: 'RegularizedGanBoat'

  net: 
    path: 'rhino.nn.baked.gan.stylegan.stylegan2_generator'
    name: 'StyleGAN2Generator'
    params:
      out_size: 256
      style_channels: 64
      noise_size: 64

  critic:
    path: 'rhino.nn.baked.gan.stylegan.stylegan2_discriminator'
    name: 'StyleGAN2Discriminator'
    params: 
      in_size: 256

  loss:
    net:
      path: 'rhino.nn.losses.gan_losses'
      name: 'LogisticGANLoss'
      params: {}

    critic:
      path: 'rhino.nn.losses.gan_losses'
      name: 'LogisticGANLoss'
      params: {}
    
optimization: 
  net:
    path: 'torch.optim'
    name: 'Adam'
    params:
      lr: 0.0002
      betas: [0.5, 0.990]
      weight_decay: 0.0
    lr_scheduler: {}

  critic:
    path: 'torch.optim'
    name: 'Adam'
    params:
      lr: 0.0001
      betas: [0.5, 0.99]
      weight_decay: 0.0
    lr_scheduler: {}

  use_ema:
    ema_decay: 0.999
    ema_start: $ema_start

_vars:

  devices: [0]

  train_batch_size: 8
  valid_batch_size: 8
  num_workers: 16

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256

  experiment_name: stylegan2_ffhq_256

  ema_start: 0