_import: configs/base/train_base_gan.yaml

_vars:

  devices: [0, 1]

  net: 
    path: 'rhino.nn.unets.pix2pix'
    name: 'UNet'
    params:
      in_ch: 3
      out_ch: 3
      base_ch: 32
      channel_mult: [1, 2, 4, 8]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      gn_groups: 16
      final_act: ~

  critic:
      path: 'rhino.nn.gan_critics.patch_gan_discriminator'
      name: 'PatchGanDiscriminator'
      params: 
        in_ch: 3
        base_ch: 32
        n_layers: 4
        spectral: true
        reduce: 'instance'

  train_batch_size: 64
  valid_batch_size: 64
  num_workers: 16

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_256
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_256

  experiment_name: pix2pix_ffhq_256

  ema_start: 0